# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20170411_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='model_pic',
            field=models.ImageField(default='/home/shishir/Pictures/images.jpg', upload_to='/home/shishir/Documents/shishir/project/static/images'),
        ),
    ]
