# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20170411_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['Created']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created',
            new_name='Created',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='isDeliever',
            new_name='IsDeliever',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='isPending',
            new_name='IsPending',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='lastBuildDate',
            new_name='LastBuildDate',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='model_pic',
            new_name='ModelPic',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='nextBuildDate',
            new_name='NextBuildDate',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='noOfHoursEstimated',
            new_name='NoOfHoursEstimated',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='noOfHoursSpent',
            new_name='NoOfHoursSpent',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='totalInvoiceValue',
            new_name='TotalInvoiceValue',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='totalProjectValue',
            new_name='TotalProjectValue',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='UserType',
        ),
        migrations.RemoveField(
            model_name='project',
            name='temp',
        ),
    ]
