# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20170418_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Id',
            new_name='id',
        ),
    ]
