# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_auto_20170418_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='NoOfHoursEstimated',
            new_name='HoursEstimated',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='NoOfHoursSpent',
            new_name='HoursSpent',
        ),
    ]
