# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_auto_20170418_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Username',
        ),
    ]
