# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_auto_20170418_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
