# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0013_user_userpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
