# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0014_userlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='action',
            new_name='Action',
        ),
        migrations.RenameField(
            model_name='userlog',
            old_name='name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='userlog',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
