# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0015_auto_20170427_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='Created',
            new_name='Time',
        ),
    ]
